package com.bugboard.dto;

/**
 * DTO for user creation by admin.
 * Contains only email and role, the temporary password is generated by the
 * system.
 */
public class CreateUserRequest {
   private String email;
   private String role; // "USER" or "ADMIN"

   public CreateUserRequest() {
   }

   public CreateUserRequest(String email, String role) {
      this.email = email;
      this.role = role;
   }

   public String getEmail() {
      return email;
   }

   public void setEmail(String email) {
      this.email = email;
   }

   public String getRole() {
      return role;
   }

   public void setRole(String role) {
      this.role = role;
   }
}
