package com.bugboard.service;

import static org.mockito.Mockito.*;
import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import com.bugboard.enums.IssueStatus;
import com.bugboard.enums.UserRole;
import com.bugboard.model.Issue;
import com.bugboard.model.User;
import com.bugboard.repository.IssueRepository;

@RunWith(MockitoJUnitRunner.class) // Lenient runner to avoid unnecessary stubbing errors
public class IssueServiceTest {
   
   @Mock
   private IssueRepository repository; // Simulate the database layer with a mock

   @InjectMocks
   private IssueService issueService; // Inject mocks into IssueService, the real service being tested

   private User admin;
   private User normalUser;
   private User reporter;

   @Before
   public void setUp() {
      // Initialize pre-conditions for tests
      admin = new User("admin@test.com", "password", UserRole.ADMIN);
      normalUser = new User("user@test.com", "password", UserRole.USER);
      reporter = new User("reporter@test.com", "password", UserRole.USER);
   }

   /**
    * TC1: Success scenario - Admin marks an open issue ad duplicate of another issue.
    * Expected Output: None
    * PostConditions: Issue status changes to CLOSED, originalIssue is linked, closedAt is set
    * to current date/time.
    */
   @Test
   public void testProcessDuplicate_TC1_Success() {
      // Arrange
      Issue duplicate = new Issue("Title for Issue A (DUPLICATE", "Description A", reporter);
      Issue original = new Issue("Title for Issue B (ORIGINAL)", "Description B", reporter);

      // We need to simulate IDs since they're generated by the DB
      // Using reflection or mocking if IDs are protected, but here we can mock the Object
      Issue spyDuplicate = spy(duplicate);
      Issue spyOriginal = spy(original);

      when(repository.findById(10L)).thenReturn(spyDuplicate);
      when(repository.findById(20L)).thenReturn(spyOriginal);

      // Act
      // Calling the functionality i chose to test
      issueService.processDuplicate(10L, 20L, admin);

      // Assert
      assertEquals("PostCond failed: Status should be CLOSED", IssueStatus.CLOSED, spyDuplicate.getStatus());
      assertNotNull("PostCond failed: closedAt should be set", spyDuplicate.getClosedAt());
      verify(repository).save(spyDuplicate); // Verify that save was called to persist changes
   }

   /**
    * TC2: Failure scenario - Non-admin user attempts to mark an issue as duplicate.
    * Expected Output: SecurityException
    */
   @Test(expected = SecurityException.class) // JUnit 4 way to expect exceptions
   public void testProcessDuplicate_TC2_SecurityException() {
      issueService.processDuplicate(10L, 20L, normalUser);
   }

   /**
    * TC3: Failure scenario - One or both IDs are null.
    * Expected Output: IllegalArgumentException
    */
   @Test(expected = IllegalArgumentException.class)
   public void testProcessDuplicate_TC3_NullIDs() {
      issueService.processDuplicate(null, 20L, admin);
   }

   /**
    * TC4: Failure scenario - Issue ID not found in repository.
    * Expected Output: IllegalArgumentException
    */
   @Test(expected = IllegalArgumentException.class)
   public void testProcessDuplicate_TC4_IssueNotFound() {
      when(repository.findById(10L)).thenReturn(null); // Faking issue 10 does not exist
      issueService.processDuplicate(10L, 20L, admin);
   }

   /**
    * TC5: Failure scenario - Attempting to mark an issue as duplicate of itself.
    * Expected Output: IllegalArgumentException
    */
   @Test(expected = IllegalArgumentException.class)
   public void testProcessDuplicate_TC5_SelfDuplication() {
      Issue issue = new Issue("Title must be long enough", "Description", reporter);
      Issue spyIssue = spy(issue);

      when(repository.findById(10L)).thenReturn(spyIssue);

      issueService.processDuplicate(10L, 10L, admin);
   }

   /**
    * TC6: Failure scenario - Attempting to mark an already closed issue as duplicate.
    * Expected Output: IllegalStateException
    */
   @Test(expected = IllegalStateException.class)
   public void testProcessDuplicate_TC6_AlreadyClosed() {
      Issue alreadyClosedIssue = new Issue("Title for Closed Issue", "Description", reporter);
      alreadyClosedIssue.setStatus(IssueStatus.CLOSED);
      Issue original = new Issue("Title for Original Issue", "Description", reporter);

      Issue spyClosed = spy(alreadyClosedIssue);
      Issue spyOriginal = spy(original);

      when(repository.findById(10L)).thenReturn(spyClosed);
      when(repository.findById(20L)).thenReturn(spyOriginal);

      issueService.processDuplicate(10L, 20L, admin);
   }
}